version: '3.5'
services:
  mediafire-app:
    container_name: media-fire
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./downloads:/app/output
