version: '3.5'
services:
  ez-mediafire:
    container_name: ez-mediafire-dl
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./downloads:/app/output
